In [41]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import zipfile

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/whats-cooking/sample_submission.csv.zip
/kaggle/input/whats-cooking/test.json.zip
/kaggle/input/whats-cooking/train.json.zip

In [42]:
zipfile.ZipFile('../input/whats-cooking/train.json.zip').extractall()
train_data = pd.read_json('/kaggle/working/train.json')
train_data.head(10)

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...
5   6602     jamaican  [plain flour, sugar, butter, eggs, fresh ginge...
6  42779      spanish  [olive oil, salt, medium shrimp, pepper, garli...
7   3735      italian  [sugar, pistachio nuts, white almond bark, flo...
8  16903      mexican  [olive oil, purple onion, fresh pineapple, por...
9  12734      italian  [chopped tomatoes, fresh basil, garlic, extra-...

In [43]:
zipfile.ZipFile('../input/whats-cooking/test.json.zip').extractall()
test_data = pd.read_json('/kaggle/working/test.json')

<h2>Data Preparation:</h2>

In [44]:
train_data["cuisine"].value_counts()

italian         7838
mexican         6438
southern_us     4320
indian          3003
chinese         2673
french          2646
cajun_creole    1546
thai            1539
japanese        1423
greek           1175
spanish          989
korean           830
vietnamese       825
moroccan         821
british          804
filipino         755
irish            667
jamaican         526
russian          489
brazilian        467
Name: cuisine, dtype: int64

In [45]:
train_data.isnull().sum()

id             0
cuisine        0
ingredients    0
dtype: int64

In [46]:
train_data["ingredients"] = train_data["ingredients"].apply(lambda x : ' '.join(map(str, x))).apply(str.lower)
test_data["ingredients"] = test_data["ingredients"].apply(lambda x : ' '.join(map(str, x))).apply(str.lower)

In [47]:
train_data

          id      cuisine                                        ingredients
0      10259        greek  romaine lettuce black olives grape tomatoes ga...
1      25693  southern_us  plain flour ground pepper salt tomatoes ground...
2      20130     filipino  eggs pepper salt mayonaise cooking oil green c...
3      22213       indian                     water vegetable oil wheat salt
4      13162       indian  black pepper shallots cornflour cayenne pepper...
...      ...          ...                                                ...
39769  29109        irish  light brown sugar granulated sugar butter warm...
39770  11462      italian  kraft zesty italian dressing purple onion broc...
39771   2238        irish  eggs citrus fruit raisins sourdough starter fl...
39772  41882      chinese  boneless chicken skinless thigh minced garlic ...
39773   2362      mexican  green chile jalapeno chilies onions ground bla...

[39774 rows x 3 columns]

In [48]:
X_train = train_data["ingredients"]
y_train = train_data["cuisine"]
X_test = test_data["ingredients"]

In [49]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X_train = vectorizer.fit_transform(X_train)

In [50]:
X_train = pd.DataFrame(data=X_train.toarray().astype(float),columns = vectorizer.get_feature_names_out())
X_train

,00,10,100,14,15,25,33,40,43,95,...,za,zatarain,zatarains,zero,zest,zesty,zinfandel,ziti,zucchini,épices
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39769,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39770,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
39771,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39772,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39773,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [51]:
X_train.shape

(39774, 3010)

In [52]:
# Get the column names that are not numeric
non_numeric_cols = [col for col in X_train.columns if not col.isnumeric()]

# Drop the columns that are not in the non_numeric_cols list
X_train = X_train.drop(columns=[col for col in X_train.columns if col not in non_numeric_cols])

In [53]:
X_train_columns = X_train.columns

In [54]:
X_train

,abalone,abbamele,absinthe,abura,acai,accent,accompaniment,achiote,acid,acini,...,za,zatarain,zatarains,zero,zest,zesty,zinfandel,ziti,zucchini,épices
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39769,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39770,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
39771,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39772,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39773,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [55]:
X_train.shape

(39774, 2999)

In [56]:
vectorizer = CountVectorizer()
X_test = vectorizer.fit_transform(X_test)

In [57]:
X_test = pd.DataFrame(data=X_test.toarray().astype(float),columns = vectorizer.get_feature_names_out())

In [59]:
# Get the column names that are not numeric
non_numeric_cols = [col for col in X_test.columns if not col.isnumeric()]

# Drop the columns that are not in the non_numeric_cols list
X_test = X_test.drop(columns=[col for col in X_test.columns if col not in non_numeric_cols])

In [60]:
X_test_columns = X_test.columns

<h2>Merge the columns of the train and test data so both have same features</h2>

In [62]:
X_test_tmp = pd.DataFrame(np.zeros((X_train.shape[0], X_test.shape[1])), columns=X_test_columns)
X_train_tmp = pd.DataFrame(np.zeros((X_test.shape[0], X_train.shape[1])), columns=X_train_columns)

In [63]:
# If a column is common in both we sum the values 
df1 = pd.concat([X_train, X_test_tmp], axis=1)
X_train = df1.groupby(df1.columns, axis=1).sum()
df2 = pd.concat([X_test, X_train_tmp], axis=1)
X_test = df2.groupby(df2.columns, axis=1).sum()

<h2>Split the Data to train and val so we can evaluate the model:</h2>

In [66]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, random_state = 42, test_size = 0.30)

<h2>Modeling</h2>

In [73]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

lr = LogisticRegression(penalty='l2')
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_train)

print(accuracy_score(y_train, lr_pred))

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.8672461477676807

In [74]:
lr_pred_val = lr.predict(X_val)
print(accuracy_score(y_val, lr_pred_val))

0.7806921981060924

In [76]:
from sklearn.metrics import classification_report
print(classification_report(y_val, lr_pred_val))

              precision    recall  f1-score   support

   brazilian       0.75      0.57      0.65       147
     british       0.64      0.49      0.55       242
cajun_creole       0.78      0.66      0.71       495
     chinese       0.79      0.83      0.81       760
    filipino       0.65      0.61      0.63       200
      french       0.61      0.61      0.61       820
       greek       0.76      0.71      0.74       354
      indian       0.87      0.89      0.88       899
       irish       0.62      0.51      0.56       207
     italian       0.81      0.89      0.85      2351
    jamaican       0.80      0.65      0.72       135
    japanese       0.80      0.71      0.75       443
      korean       0.81      0.76      0.78       249
     mexican       0.90      0.91      0.91      1957
    moroccan       0.79      0.74      0.77       237
     russian       0.53      0.46      0.49       144
 southern_us       0.71      0.79      0.75      1289
     spanish       0.59      0.51      0.55       282
        thai       0.81      0.77      0.79       484
  vietnamese       0.69      0.60      0.64       238

    accuracy                           0.78     11933
   macro avg       0.73      0.68      0.71     11933
weighted avg       0.78      0.78      0.78     11933

In [77]:
predictions = lr.predict(X_test)